--drop table iis_statuscodes 

create table iis_statuscodes ( code nvarchar(10), [description] nvarchar(max) )

insert into iis_statuscodes
select '100', 'Continue.'3
union all select '101', 'Switching protocols.'
union all select '200', 'OK. The client request has succeeded.'
union all select '201', 'Created.'
union all select '202', 'Accepted.'
union all select '203', 'Nonauthoritative information.'
union all select '204', 'No content.'
union all select '205', 'Reset content.'
union all select '206', 'Partial content.'
union all select '301', 'Moved permanently.'
union all select '302', 'Object moved.'
union all select '304', 'Not modified.'
union all select '307', 'Temporary redirect.'
union all select '400.1', 'Invalid Destination Header.'
union all select '400.2', 'Invalid Depth Header.'
union all select '400.3', 'Invalid If Header.'
union all select '400.4', 'Invalid Overwrite Header.'
union all select '400.5', 'Invalid Translate Header.'
union all select '400.6', 'Invalid Request Body.'
union all select '400.7', 'Invalid Content Length.'
union all select '400.8', 'Invalid Timeout.'
union all select '400.9', 'Invalid Lock Token.'
union all select '401', 'Access denied.'
union all select '401.1', 'Logon failed.'
union all select '401.2', 'Logon failed due to server configuration.'
union all select '401.3', 'Unauthorized due to ACL on resource.'
union all select '401.4', 'Authorization failed by filter.'
union all select '401.5', 'Authorization failed by ISAPI/CGI application.'
union all select '403', 'Forbidden.'
union all select '403.1', 'Execute access forbidden.'
union all select '403.2', 'Read access forbidden.'
union all select '403.3', 'Write access forbidden.'
union all select '403.4', 'SSL required.'
union all select '403.5', 'SSL 128 required.'
union all select '403.6', 'IP address rejected.'
union all select '403.7', 'Client certificate required.'
union all select '403.8', 'Site access denied.'
union all select '403.9', 'Forbidden: Too many clients are trying to connect to the Web server.'
union all select '403.1', 'Forbidden: Web server is configured to deny Execute access.'
union all select '403.11', 'Forbidden: Password has been changed.'
union all select '403.12', 'Mapper denied access.'
union all select '403.13', 'Client certificate revoked.'
union all select '403.14', 'Directory listing denied.'
union all select '403.15', 'Forbidden: Client access licenses have exceeded limits on the Web server.'
union all select '403.16', 'Client certificate is untrusted or invalid.'
union all select '403.17', 'Client certificate has expired or is not yet valid.'
union all select '403.18', 'Cannot execute requested URL in the current application pool.'
union all select '403.19', 'Cannot execute CGI applications for the client in this application pool.'
union all select '403.2', 'Forbidden: Passport logon failed.'
union all select '403.21', 'Forbidden: Source access denied.'
union all select '403.22', 'Forbidden: Infinite depth is denied.'
union all select '403.502', 'Forbidden: Too many requests from the same client IP; Dynamic IP Restriction limit reached.'
union all select '404', 'Not found.'
union all select '404', 'Not found.'
union all select '404.1', 'Site Not Found.'
union all select '404.2', 'ISAPI or CGI restriction.'
union all select '404.3', 'MIME type restriction.'
union all select '404.4', 'No handler configured.'
union all select '404.5', 'Denied by request filtering configuration.'
union all select '404.6', 'Verb denied.'
union all select '404.7', 'File extension denied.'
union all select '404.8', 'Hidden namespace.'
union all select '404.9', 'File attribute hidden.'
union all select '404.1', 'Request header too long.'
union all select '404.11', 'Request contains double escape sequence.'
union all select '404.12', 'Request contains high-bit characters.'
union all select '404.13', 'Content length too large.'
union all select '404.14', 'Request URL too long.'
union all select '404.15', 'Query string too long.'
union all select '404.16', 'DAV request sent to the static file handler.'
union all select '404.17', 'Dynamic content mapped to the static file handler via a wildcard MIME mapping.'
union all select '404.18', 'Querystring sequence denied.'
union all select '404.19', 'Denied by filtering rule.'
union all select '404.2', 'Too Many URL Segments'
union all select '405', 'Method Not Allowed.'
union all select '406', 'Client browser does not accept the MIME type of the requested page.'
union all select '408', 'Request timed out.'
union all select '412', 'Precondition failed.'
union all select '500', 'Internal server error.'
union all select '500', 'Module or ISAPI error occurred.'
union all select '500.11', 'Application is shutting down on the Web server.'
union all select '500.12', 'Application is busy restarting on the Web server.'
union all select '500.13', 'Web server is too busy.'
union all select '500.15', 'Direct requests for Global.asax are not allowed.'
union all select '500.19', 'Configuration data is invalid.'
union all select '500.21', ' Module not recognized.'
union all select '500.22', 'An ASP.NET httpModules configuration does not apply in Managed Pipeline mode.'
union all select '500.23', 'An ASP.NET httpHandlers configuration does not apply in Managed Pipeline mode.'
union all select '500.24', 'An ASP.NET impersonation configuration does not apply in Managed Pipeline mode.'
union all select '500.5', ' A rewrite error occurred during RQ_BEGIN_REQUEST notification handling. A configuration or inbound rule execution error occurred.'
union all select '500.51', 'A rewrite error occurred during GL_PRE_BEGIN_REQUEST notification handling. A global configuration or global rule execution error occurred.'
union all select '500.52', 'A rewrite error occurred during RQ_SEND_RESPONSE notification handling. An outbound rule execution occurred.'
union all select '500.53', 'A rewrite error occurred during RQ_RELEASE_REQUEST_STATE notification handling. An outbound rule execution error occurred. The rule is configured to be executed before the output user cache gets updated.'
union all select '500.1', 'Internal ASP error.'
union all select '501', 'Header values specify a configuration that is not implemented.'
union all select '502', 'Web server received an invalid response while acting as a gateway or proxy.'
union all select '502.1', 'CGI application timeout.'
union all select '502.2', 'Bad gateway.'
union all select '503', 'Service unavailable.'
union all select '503', 'Application pool unavailable.'
union all select '503.2', 'Concurrent request limit exceeded.'
