C07C, E01E, N02B
SELECT TIME, PAGE, QUERYSTRING
FROM IIS0506
WHERE PAGE LIKE '%/TORONTO/%'
AND PAGE NOT LIKE '%/UPLOAD%'
AND ( QUERYSTRING LIKE '%w05b%'
OR QUERYSTRING LIKE '%mfstid=468%' 
	)
ORDER BY TIME ASC



SELECT TIME, PAGE, QUERYSTRING
FROM IIS0510
WHERE PAGE LIKE '%/TORONTO/%'
AND PAGE NOT LIKE '%/UPLOAD%'
AND ( QUERYSTRING LIKE '%C07C%'
OR QUERYSTRING LIKE '%mfstid=388%' 
	)
ORDER BY TIME ASC